# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Information(object):
    def setupUi(self, Information):
        Information.setObjectName("Information")
        Information.resize(442, 253)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/backgrounds/hands.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Information.setWindowIcon(icon)
        Information.setStyleSheet("\n"
"QWidget#widget\n"
"{\n"
"background-color:#6fa844 ;\n"
"}\n"
"QFrame#main_frame{\n"
"background-image: url(:/icons/Background2.jpg);\n"
"\n"
"background-position:center;\n"
"background-repeat:no-repeat;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Information)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Information)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_frame = QtWidgets.QFrame(self.widget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header_frame = QtWidgets.QFrame(self.main_frame)
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.RAAS_label = QtWidgets.QLabel(self.header_frame)
        self.RAAS_label.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.RAAS_label.setStyleSheet("color: rgb(48, 78, 151);\n"
"font:12pt \"Bahnschrift SemiBold\";")
        self.RAAS_label.setObjectName("RAAS_label")
        self.ET_label = QtWidgets.QLabel(self.header_frame)
        self.ET_label.setGeometry(QtCore.QRect(0, 20, 241, 16))
        self.ET_label.setStyleSheet("color: rgb(48, 78, 151);\n"
"font: 10pt \"Bahnschrift Light\";")
        self.ET_label.setWordWrap(True)
        self.ET_label.setObjectName("ET_label")
        self.verticalLayout_3.addWidget(self.header_frame)
        self.body_frame = QtWidgets.QFrame(self.main_frame)
        self.body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_frame.setObjectName("body_frame")
        self.label = QtWidgets.QLabel(self.body_frame)
        self.label.setGeometry(QtCore.QRect(10, 9, 361, 51))
        self.label.setStyleSheet("font: 12pt \"Bahnschrift Light\";")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.body_frame)
        self.footer_frame = QtWidgets.QFrame(self.main_frame)
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.footer_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.login_btn = QtWidgets.QPushButton(self.footer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.login_btn.setMaximumSize(QtCore.QSize(70, 40))
        self.login_btn.setStyleSheet("background-color: rgb(111, 168, 68);\n"
"border-radius: 15px;\n"
"color: rgb(241, 241, 241);\n"
"font:  bold 10pt \"Bahnschrift Light\";margin:5px;\n"
"vertical-align: center;\n"
"horizontal-align: center;")
        self.login_btn.setAutoDefault(False)
        self.login_btn.setFlat(False)
        self.login_btn.setObjectName("login_btn")
        self.gridLayout.addWidget(self.login_btn, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.footer_frame)
        self.verticalLayout_2.addWidget(self.main_frame)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Information)
        QtCore.QMetaObject.connectSlotsByName(Information)

    def retranslateUi(self, Information):
        _translate = QtCore.QCoreApplication.translate
        Information.setWindowTitle(_translate("Information", "Dialog"))
        self.RAAS_label.setText(_translate("Information", "RAAS"))
        self.ET_label.setText(_translate("Information", "INSTITUTE OF EMERGING TECHNOLOGIES"))
        self.label.setText(_translate("Information", "Your message will display here."))
        self.login_btn.setText(_translate("Information", "OK"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Information = QtWidgets.QDialog()
    ui = Ui_Information()
    ui.setupUi(Information)
    Information.show()
    sys.exit(app.exec_())
