# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entry_test_quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EntryTest(object):
    def setupUi(self, EntryTest):
        EntryTest.setObjectName("EntryTest")
        EntryTest.resize(1024, 640)
        EntryTest.setMinimumSize(QtCore.QSize(1024, 640))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/backgrounds/hands.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EntryTest.setWindowIcon(icon)
        EntryTest.setStyleSheet("QFrame#login_form{\n"
"background-color: rgb(48, 78, 151);\n"
"border-radius:40px;\n"
"margin: 60px;\n"
"}\n"
"QFrame#border_frame\n"
"{\n"
"background-color:#6fa844 ;\n"
"}\n"
"QFrame#main_frame{\n"
"background-image: url(:/icons/Background2.jpg);\n"
"\n"
"background-position:center;\n"
"background-repeat:no-repeat;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(EntryTest)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.border_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_frame.sizePolicy().hasHeightForWidth())
        self.border_frame.setSizePolicy(sizePolicy)
        self.border_frame.setStyleSheet("")
        self.border_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_frame.setObjectName("border_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.border_frame)
        self.verticalLayout_2.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_frame = QtWidgets.QFrame(self.border_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_frame.setStyleSheet("")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 120))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.header_frame.setStyleSheet("")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.header_gridLayout = QtWidgets.QGridLayout()
        self.header_gridLayout.setObjectName("header_gridLayout")
        self.hunar_logo = QtWidgets.QLabel(self.header_frame)
        self.hunar_logo.setMinimumSize(QtCore.QSize(70, 100))
        self.hunar_logo.setMaximumSize(QtCore.QSize(70, 100))
        self.hunar_logo.setStyleSheet("\n"
"background-image: url(:/icons/icons/backgrounds/Asset 7-100.jpg);\n"
"background-repeat: no-repeat; \n"
" background-position: right;\n"
"margin:5px;\n"
"")
        self.hunar_logo.setText("")
        self.hunar_logo.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.hunar_logo.setObjectName("hunar_logo")
        self.header_gridLayout.addWidget(self.hunar_logo, 0, 0, 2, 1)
        self.RAAS_label = QtWidgets.QLabel(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAAS_label.sizePolicy().hasHeightForWidth())
        self.RAAS_label.setSizePolicy(sizePolicy)
        self.RAAS_label.setMinimumSize(QtCore.QSize(120, 0))
        self.RAAS_label.setStyleSheet("color: rgb(48, 78, 151);\n"
"font: 63 32pt \"Bahnschrift SemiBold\";")
        self.RAAS_label.setObjectName("RAAS_label")
        self.header_gridLayout.addWidget(self.RAAS_label, 0, 1, 1, 1)
        self.std_name_label = QtWidgets.QLabel(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.std_name_label.sizePolicy().hasHeightForWidth())
        self.std_name_label.setSizePolicy(sizePolicy)
        self.std_name_label.setMinimumSize(QtCore.QSize(130, 0))
        self.std_name_label.setStyleSheet("font: 14pt \"Bahnschrift SemiBold\";\n"
"")
        self.std_name_label.setObjectName("std_name_label")
        self.header_gridLayout.addWidget(self.std_name_label, 0, 2, 1, 1)
        self.disp_std_name_label = QtWidgets.QLabel(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disp_std_name_label.sizePolicy().hasHeightForWidth())
        self.disp_std_name_label.setSizePolicy(sizePolicy)
        self.disp_std_name_label.setStyleSheet("color: rgb(74, 74, 74);\n"
"font: 14pt \"Bahnschrift SemiBold\";\n"
"")
        self.disp_std_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.disp_std_name_label.setWordWrap(True)
        self.disp_std_name_label.setObjectName("disp_std_name_label")
        self.header_gridLayout.addWidget(self.disp_std_name_label, 0, 3, 1, 2)
        self.ET_label = QtWidgets.QLabel(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ET_label.sizePolicy().hasHeightForWidth())
        self.ET_label.setSizePolicy(sizePolicy)
        self.ET_label.setMinimumSize(QtCore.QSize(541, 0))
        self.ET_label.setStyleSheet("color: rgb(48, 78, 151);\n"
"font: 25 22pt \"Bahnschrift Light\";")
        self.ET_label.setWordWrap(True)
        self.ET_label.setObjectName("ET_label")
        self.header_gridLayout.addWidget(self.ET_label, 1, 1, 1, 1)
        self.time_label = QtWidgets.QLabel(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_label.sizePolicy().hasHeightForWidth())
        self.time_label.setSizePolicy(sizePolicy)
        self.time_label.setMinimumSize(QtCore.QSize(120, 0))
        self.time_label.setStyleSheet("font: 14pt \"Bahnschrift SemiBold\";")
        self.time_label.setObjectName("time_label")
        self.header_gridLayout.addWidget(self.time_label, 1, 2, 1, 2)
        self.disp_time_label = QtWidgets.QLabel(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disp_time_label.sizePolicy().hasHeightForWidth())
        self.disp_time_label.setSizePolicy(sizePolicy)
        self.disp_time_label.setMinimumSize(QtCore.QSize(0, 30))
        self.disp_time_label.setStyleSheet("\n"
"color: rgb(255, 0, 0);\n"
"font: 14pt \"Bahnschrift SemiBold\";")
        self.disp_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.disp_time_label.setWordWrap(True)
        self.disp_time_label.setObjectName("disp_time_label")
        self.header_gridLayout.addWidget(self.disp_time_label, 1, 4, 1, 1)
        self.horizontalLayout.addLayout(self.header_gridLayout)
        self.verticalLayout_3.addWidget(self.header_frame)
        self.navigation_bar_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navigation_bar_frame.sizePolicy().hasHeightForWidth())
        self.navigation_bar_frame.setSizePolicy(sizePolicy)
        self.navigation_bar_frame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.navigation_bar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navigation_bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navigation_bar_frame.setObjectName("navigation_bar_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.navigation_bar_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.entry_test_label = QtWidgets.QLabel(self.navigation_bar_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_test_label.sizePolicy().hasHeightForWidth())
        self.entry_test_label.setSizePolicy(sizePolicy)
        self.entry_test_label.setMinimumSize(QtCore.QSize(541, 0))
        self.entry_test_label.setStyleSheet("color: rgb(48, 78, 151);\n"
"font:20pt \"Bahnschrift Light\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.0340909 rgba(0, 0, 255, 255), stop:0.204545 rgba(255, 255, 255, 255), stop:0.318182 rgba(0, 170, 0, 255), stop:0.522727 rgba(255, 255, 255, 255), stop:0.727273 rgba(0, 0, 255, 255), stop:0.926136 rgba(0, 170, 0, 255));\n"
"")
        self.entry_test_label.setAlignment(QtCore.Qt.AlignCenter)
        self.entry_test_label.setWordWrap(True)
        self.entry_test_label.setObjectName("entry_test_label")
        self.gridLayout_2.addWidget(self.entry_test_label, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.navigation_bar_frame)
        self.quiz_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quiz_frame.sizePolicy().hasHeightForWidth())
        self.quiz_frame.setSizePolicy(sizePolicy)
        self.quiz_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.quiz_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quiz_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quiz_frame.setObjectName("quiz_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.quiz_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.quiz_gridLayout = QtWidgets.QGridLayout()
        self.quiz_gridLayout.setObjectName("quiz_gridLayout")
        self.question_heading_label = QtWidgets.QLabel(self.quiz_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_heading_label.sizePolicy().hasHeightForWidth())
        self.question_heading_label.setSizePolicy(sizePolicy)
        self.question_heading_label.setStyleSheet("color: rgb(48, 78, 151);\n"
"font: 18pt \"Bahnschrift SemiBold\";")
        self.question_heading_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.question_heading_label.setObjectName("question_heading_label")
        self.quiz_gridLayout.addWidget(self.question_heading_label, 0, 0, 1, 1)
        self.question_image_label = QtWidgets.QLabel(self.quiz_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_image_label.sizePolicy().hasHeightForWidth())
        self.question_image_label.setSizePolicy(sizePolicy)
        self.question_image_label.setMinimumSize(QtCore.QSize(300, 131))
        self.question_image_label.setStyleSheet("color: rgb(241, 241, 241);\n"
"background-image: url(:/icons/icons/white/image.svg);\n"
"background-repeat:no-repeat;\n"
"background-position:center;\n"
"font: 18pt \"Georgia\";")
        self.question_image_label.setText("")
        self.question_image_label.setScaledContents(True)
        self.question_image_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.question_image_label.setWordWrap(True)
        self.question_image_label.setObjectName("question_image_label")
        self.quiz_gridLayout.addWidget(self.question_image_label, 0, 1, 2, 1)
        self.question_display_label = QtWidgets.QLabel(self.quiz_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_display_label.sizePolicy().hasHeightForWidth())
        self.question_display_label.setSizePolicy(sizePolicy)
        self.question_display_label.setMinimumSize(QtCore.QSize(550, 100))
        self.question_display_label.setStyleSheet("color: rgb(48, 78, 151);\n"
"font:14pt \"Bahnschrift SemiBold\";")
        self.question_display_label.setScaledContents(True)
        self.question_display_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.question_display_label.setWordWrap(True)
        self.question_display_label.setObjectName("question_display_label")
        self.quiz_gridLayout.addWidget(self.question_display_label, 1, 0, 1, 1)
        self.option1_radioButton = QtWidgets.QRadioButton(self.quiz_frame)
        self.option1_radioButton.setMinimumSize(QtCore.QSize(550, 0))
        self.option1_radioButton.setStyleSheet("font: 14pt \"Bahnschrift SemiBold\";\n"
"background-repeat:no-repeat;\n"
"background-position: center;\n"
"color: rgb(48, 78, 151);")
        self.option1_radioButton.setIconSize(QtCore.QSize(16, 16))
        self.option1_radioButton.setObjectName("option1_radioButton")
        self.quiz_gridLayout.addWidget(self.option1_radioButton, 2, 0, 1, 1)
        self.option2_radioButton = QtWidgets.QRadioButton(self.quiz_frame)
        self.option2_radioButton.setMinimumSize(QtCore.QSize(550, 0))
        self.option2_radioButton.setStyleSheet("font: 14pt \"Bahnschrift SemiBold\";\n"
"background-repeat:no-repeat;\n"
"background-position: center;\n"
"color: rgb(48, 78, 151);")
        self.option2_radioButton.setObjectName("option2_radioButton")
        self.quiz_gridLayout.addWidget(self.option2_radioButton, 3, 0, 1, 1)
        self.option3_radioButton = QtWidgets.QRadioButton(self.quiz_frame)
        self.option3_radioButton.setMinimumSize(QtCore.QSize(550, 0))
        self.option3_radioButton.setStyleSheet("font: 14pt \"Bahnschrift SemiBold\";\n"
"background-repeat:no-repeat;\n"
"background-position: center;\n"
"color: rgb(48, 78, 151);")
        self.option3_radioButton.setObjectName("option3_radioButton")
        self.quiz_gridLayout.addWidget(self.option3_radioButton, 4, 0, 1, 1)
        self.option4_radioButton = QtWidgets.QRadioButton(self.quiz_frame)
        self.option4_radioButton.setMinimumSize(QtCore.QSize(550, 0))
        self.option4_radioButton.setStyleSheet("font: 14pt \"Bahnschrift SemiBold\";\n"
"background-repeat:no-repeat;\n"
"background-position: center;\n"
"color: rgb(48, 78, 151);")
        self.option4_radioButton.setObjectName("option4_radioButton")
        self.quiz_gridLayout.addWidget(self.option4_radioButton, 5, 0, 1, 1)
        self.next_btn = QtWidgets.QPushButton(self.quiz_frame)
        self.next_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.next_btn.setMaximumSize(QtCore.QSize(100, 40))
        self.next_btn.setStyleSheet("background-color:  rgb(48, 78, 151);\n"
"\n"
"\n"
"font: 12pt \"Bahnschrift SemiBold\";\n"
"border-radius: 20px;\n"
"color: rgb(241, 241, 241);\n"
"")
        self.next_btn.setObjectName("next_btn")
        self.quiz_gridLayout.addWidget(self.next_btn, 6, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.quiz_gridLayout)
        self.verticalLayout_3.addWidget(self.quiz_frame)
        self.verticalLayout_2.addWidget(self.main_frame)
        self.verticalLayout.addWidget(self.border_frame)
        EntryTest.setCentralWidget(self.centralwidget)

        self.retranslateUi(EntryTest)
        QtCore.QMetaObject.connectSlotsByName(EntryTest)

    def retranslateUi(self, EntryTest):
        _translate = QtCore.QCoreApplication.translate
        EntryTest.setWindowTitle(_translate("EntryTest", "MainWindow"))
        self.RAAS_label.setText(_translate("EntryTest", "RAAS"))
        self.std_name_label.setText(_translate("EntryTest", "Student Name:"))
        self.disp_std_name_label.setText(_translate("EntryTest", "Javeria Hassan"))
        self.ET_label.setText(_translate("EntryTest", "INSTITUTE OF EMERGING TECHNOLOGIES"))
        self.time_label.setText(_translate("EntryTest", "Time Remaining:"))
        self.disp_time_label.setText(_translate("EntryTest", "03:34"))
        self.entry_test_label.setText(_translate("EntryTest", "ENTRY TEST"))
        self.question_heading_label.setText(_translate("EntryTest", "QUESTION:"))
        self.question_display_label.setText(_translate("EntryTest", "What is your city name?"))
        self.option1_radioButton.setText(_translate("EntryTest", "Karachi"))
        self.option2_radioButton.setText(_translate("EntryTest", "Lahore"))
        self.option3_radioButton.setText(_translate("EntryTest", "Islamabad"))
        self.option4_radioButton.setText(_translate("EntryTest", "Peshawer"))
        self.next_btn.setText(_translate("EntryTest", "Next"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EntryTest = QtWidgets.QMainWindow()
    ui = Ui_EntryTest()
    ui.setupUi(EntryTest)
    EntryTest.show()
    sys.exit(app.exec_())
