# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instructions.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Instructions(object):
    def setupUi(self, Instructions):
        Instructions.setObjectName("Instructions")
        Instructions.resize(1024, 644)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/backgrounds/hands.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Instructions.setWindowIcon(icon)
        Instructions.setStyleSheet("QFrame#instructions_form{\n"
                                   "background-color: rgb(48, 78, 151);\n"
                                   "border-radius:40px;\n"
                                   "margin: 25px;\n"
                                   "}\n"
                                   "QFrame#border_frame\n"
                                   "{\n"
                                   "background-color:#6fa844 ;\n"
                                   "}\n"
                                   "QFrame#main_frame{\n"
                                   "background-image: url(:/icons/Background2.jpg);\n"
                                   "\n"
                                   "background-position:center;\n"
                                   "background-repeat:no-repeat;\n"
                                   "}\n"
                                   "")
        self.centralwidget = QtWidgets.QWidget(Instructions)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.border_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_frame.sizePolicy().hasHeightForWidth())
        self.border_frame.setSizePolicy(sizePolicy)
        self.border_frame.setStyleSheet("")
        self.border_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_frame.setObjectName("border_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.border_frame)
        self.verticalLayout_2.setContentsMargins(80, 80, 80, 80)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_frame = QtWidgets.QFrame(self.border_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_frame.setStyleSheet("")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.heading_side_bar = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heading_side_bar.sizePolicy().hasHeightForWidth())
        self.heading_side_bar.setSizePolicy(sizePolicy)
        self.heading_side_bar.setMinimumSize(QtCore.QSize(240, 0))
        self.heading_side_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.heading_side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.heading_side_bar.setLineWidth(0)
        self.heading_side_bar.setObjectName("heading_side_bar")
        self.RAAS_heading_label = QtWidgets.QLabel(self.heading_side_bar)
        self.RAAS_heading_label.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.RAAS_heading_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                              "font: 63 32pt \"Bahnschrift SemiBold\";")
        self.RAAS_heading_label.setObjectName("RAAS_heading_label")
        self.ET_label = QtWidgets.QLabel(self.heading_side_bar)
        self.ET_label.setGeometry(QtCore.QRect(10, 60, 221, 101))
        self.ET_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                    "font: 25 22pt \"Bahnschrift Light\";")
        self.ET_label.setWordWrap(True)
        self.ET_label.setObjectName("ET_label")
        self.horizontalLayout.addWidget(self.heading_side_bar)
        self.instructions_form = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instructions_form.sizePolicy().hasHeightForWidth())
        self.instructions_form.setSizePolicy(sizePolicy)
        self.instructions_form.setMinimumSize(QtCore.QSize(470, 480))
        self.instructions_form.setMaximumSize(QtCore.QSize(16777215, 800))
        self.instructions_form.setStyleSheet("")
        self.instructions_form.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.instructions_form.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.instructions_form.setLineWidth(0)
        self.instructions_form.setObjectName("instructions_form")
        self.welcome_heading = QtWidgets.QLabel(self.instructions_form)
        self.welcome_heading.setGeometry(QtCore.QRect(20, 70, 421, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_heading.sizePolicy().hasHeightForWidth())
        self.welcome_heading.setSizePolicy(sizePolicy)
        self.welcome_heading.setStyleSheet("color: rgb(241, 241, 241);\n"
                                           "font: 63 20pt \"Bahnschrift SemiBold\";\n"
                                           "margin:5px;")
        self.welcome_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_heading.setWordWrap(True)
        self.welcome_heading.setObjectName("welcome_heading")
        self.choose_your_test_label = QtWidgets.QLabel(self.instructions_form)
        self.choose_your_test_label.setGeometry(QtCore.QRect(90, 120, 281, 39))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_your_test_label.sizePolicy().hasHeightForWidth())
        self.choose_your_test_label.setSizePolicy(sizePolicy)
        self.choose_your_test_label.setStyleSheet("color: rgb(241, 241, 241);\n"
                                                  "\n"
                                                  "font: 25 18pt \"Bahnschrift Light Condensed\";\n"
                                                  "margin:5px;")
        self.choose_your_test_label.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_your_test_label.setObjectName("choose_your_test_label")
        self.ins_2 = QtWidgets.QLabel(self.instructions_form)
        self.ins_2.setGeometry(QtCore.QRect(30, 230, 371, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ins_2.sizePolicy().hasHeightForWidth())
        self.ins_2.setSizePolicy(sizePolicy)
        self.ins_2.setStyleSheet("color: rgb(241, 241, 241);\n"
                                 "font: 14pt \"Bahnschrift Light Condensed\";\n"
                                 "margin:5px;")
        self.ins_2.setObjectName("ins_2")
        self.ins_3 = QtWidgets.QLabel(self.instructions_form)
        self.ins_3.setGeometry(QtCore.QRect(30, 260, 381, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ins_3.sizePolicy().hasHeightForWidth())
        self.ins_3.setSizePolicy(sizePolicy)
        self.ins_3.setStyleSheet("color: rgb(241, 241, 241);\n"
                                 "font: 14pt \"Bahnschrift Light Condensed\";\n"
                                 "margin:5px;")
        self.ins_3.setObjectName("ins_3")
        self.ins_4 = QtWidgets.QLabel(self.instructions_form)
        self.ins_4.setGeometry(QtCore.QRect(30, 290, 401, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ins_4.sizePolicy().hasHeightForWidth())
        self.ins_4.setSizePolicy(sizePolicy)
        self.ins_4.setStyleSheet("color: rgb(241, 241, 241);\n"
                                 "font: 14pt \"Bahnschrift Light Condensed\";\n"
                                 "margin:5px;")
        self.ins_4.setWordWrap(True)
        self.ins_4.setObjectName("ins_4")
        self.ins_5 = QtWidgets.QLabel(self.instructions_form)
        self.ins_5.setGeometry(QtCore.QRect(30, 320, 341, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ins_5.sizePolicy().hasHeightForWidth())
        self.ins_5.setSizePolicy(sizePolicy)
        self.ins_5.setStyleSheet("color: rgb(241, 241, 241);\n"
                                 "font: 14pt \"Bahnschrift Light Condensed\";\n"
                                 "margin:5px;")
        self.ins_5.setObjectName("ins_5")
        self.info_label = QtWidgets.QLabel(self.instructions_form)
        self.info_label.setGeometry(QtCore.QRect(30, 160, 391, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_label.sizePolicy().hasHeightForWidth())
        self.info_label.setSizePolicy(sizePolicy)
        self.info_label.setStyleSheet("color: rgb(241, 241, 241);\n"
                                      "font: 14pt \"Bahnschrift Light Condensed\";\n"
                                      "margin:5px;")
        self.info_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.ins_1 = QtWidgets.QLabel(self.instructions_form)
        self.ins_1.setGeometry(QtCore.QRect(30, 200, 381, 31))
        self.ins_1.setStyleSheet("color: rgb(241, 241, 241);\n"
                                 "font: 14pt \"Bahnschrift Light Condensed\";\n"
                                 "margin:5px;")
        self.ins_1.setObjectName("ins_1")
        self.class_test_btn = QtWidgets.QPushButton(self.instructions_form)
        self.class_test_btn.setGeometry(QtCore.QRect(180, 370, 100, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.class_test_btn.sizePolicy().hasHeightForWidth())
        self.class_test_btn.setSizePolicy(sizePolicy)
        self.class_test_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.class_test_btn.setMaximumSize(QtCore.QSize(100, 40))
        self.class_test_btn.setStyleSheet("background-color: rgb(111, 168, 68);\n"
                                          "border-radius: 15px;\n"
                                          "color: rgb(241, 241, 241);\n"
                                          "font:  bold 10pt \"Bahnschrift Light\";margin:5px;\n"
                                          "vertical-align: center;\n"
                                          "horizontal-align: center;")
        self.class_test_btn.setAutoDefault(False)
        self.class_test_btn.setFlat(False)
        self.class_test_btn.setObjectName("class_test_btn")
        self.horizontalLayout.addWidget(self.instructions_form, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.logo_side_bar = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_side_bar.sizePolicy().hasHeightForWidth())
        self.logo_side_bar.setSizePolicy(sizePolicy)
        self.logo_side_bar.setMinimumSize(QtCore.QSize(150, 0))
        self.logo_side_bar.setStyleSheet("")
        self.logo_side_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_side_bar.setLineWidth(0)
        self.logo_side_bar.setObjectName("logo_side_bar")
        self.gridLayout = QtWidgets.QGridLayout(self.logo_side_bar)
        self.gridLayout.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.hunar_logo = QtWidgets.QLabel(self.logo_side_bar)
        self.hunar_logo.setMinimumSize(QtCore.QSize(80, 120))
        self.hunar_logo.setMaximumSize(QtCore.QSize(80, 120))
        self.hunar_logo.setStyleSheet("background-image: url(:/icons/icons/backgrounds/Asset 7-100.jpg);\n"
                                      "background-repeat: no-repeat; \n"
                                      " background-position: right;\n"
                                      "margin:5px;\n"
                                      "")
        self.hunar_logo.setText("")
        self.hunar_logo.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing)
        self.hunar_logo.setObjectName("hunar_logo")
        self.gridLayout.addWidget(self.hunar_logo, 0, 0, 1, 1, QtCore.Qt.AlignRight | QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.logo_side_bar)
        self.verticalLayout_2.addWidget(self.main_frame)
        self.verticalLayout.addWidget(self.border_frame)
        Instructions.setCentralWidget(self.centralwidget)

        self.retranslateUi(Instructions)
        QtCore.QMetaObject.connectSlotsByName(Instructions)

    def retranslateUi(self, Instructions):
        _translate = QtCore.QCoreApplication.translate
        Instructions.setWindowTitle(_translate("Instructions", "MainWindow"))
        self.RAAS_heading_label.setText(_translate("Instructions", "RAAS"))
        self.ET_label.setText(_translate("Instructions", "INSTITUTE OF EMERGING TECHNOLOGIES"))
        self.welcome_heading.setText(_translate("Instructions", "WELCOME TO THE TEST PORTAL"))
        self.choose_your_test_label.setText(_translate("Instructions", "Instructions for Entry Test Exam"))
        self.ins_2.setText(_translate("Instructions", "ii.  Each question carries 1 mark and 1 minute."))
        self.ins_3.setText(_translate("Instructions", "iii. Complete the exam in time limit."))
        self.ins_4.setText(_translate("Instructions", "iv. While attemping the quiz, do not close the application."))
        self.ins_5.setText(_translate("Instructions", "v. Finish the quiz in one attempt."))
        self.info_label.setText(_translate("Instructions", "Kindly read instructions below before starting your test:"))
        self.ins_1.setText(_translate("Instructions", "i.  Attempt all questions."))
        self.class_test_btn.setText(_translate("Instructions", "Start Quiz"))


import icon_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Instructions = QtWidgets.QMainWindow()
    ui = Ui_Instructions()
    ui.setupUi(Instructions)
    Instructions.show()
    sys.exit(app.exec_())
