# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_portal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentPortal(object):
    def setupUi(self, StudentPortal):
        StudentPortal.setObjectName("StudentPortal")
        StudentPortal.resize(1024, 641)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/backgrounds/hands.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StudentPortal.setWindowIcon(icon)
        StudentPortal.setStyleSheet("QFrame#login_form{\n"
                                    "background-color: rgb(48, 78, 151);\n"
                                    "border-radius:40px;\n"
                                    "margin: 60px;\n"
                                    "}\n"
                                    "QFrame#border_frame\n"
                                    "{\n"
                                    "background-color:#6fa844 ;\n"
                                    "}\n"
                                    "QFrame#main_frame{\n"
                                    "background-image: url(:/icons/Background2.jpg);\n"
                                    "\n"
                                    "background-position:center;\n"
                                    "background-repeat:no-repeat;\n"
                                    "}\n"
                                    "")
        self.centralwidget = QtWidgets.QWidget(StudentPortal)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.border_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_frame.sizePolicy().hasHeightForWidth())
        self.border_frame.setSizePolicy(sizePolicy)
        self.border_frame.setStyleSheet("")
        self.border_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_frame.setObjectName("border_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.border_frame)
        self.gridLayout_6.setContentsMargins(40, 40, 40, 40)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.main_frame = QtWidgets.QFrame(self.border_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_frame.setStyleSheet("")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 140))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.header_frame.setStyleSheet("")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.hunar_logo = QtWidgets.QLabel(self.header_frame)
        self.hunar_logo.setMinimumSize(QtCore.QSize(70, 100))
        self.hunar_logo.setMaximumSize(QtCore.QSize(70, 100))
        self.hunar_logo.setStyleSheet("\n"
                                      "background-image: url(:/icons/icons/backgrounds/Asset 7-100.jpg);\n"
                                      "background-repeat: no-repeat; \n"
                                      " background-position: right;\n"
                                      "margin:5px;\n"
                                      "")
        self.hunar_logo.setText("")
        self.hunar_logo.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing)
        self.hunar_logo.setObjectName("hunar_logo")
        self.gridLayout_3.addWidget(self.hunar_logo, 0, 0, 2, 1)
        self.RAAS_label = QtWidgets.QLabel(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAAS_label.sizePolicy().hasHeightForWidth())
        self.RAAS_label.setSizePolicy(sizePolicy)
        self.RAAS_label.setMinimumSize(QtCore.QSize(120, 0))
        self.RAAS_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                      "font: 63 32pt \"Bahnschrift SemiBold\";")
        self.RAAS_label.setObjectName("RAAS_label")
        self.gridLayout_3.addWidget(self.RAAS_label, 0, 1, 1, 1)
        self.ET_label = QtWidgets.QLabel(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ET_label.sizePolicy().hasHeightForWidth())
        self.ET_label.setSizePolicy(sizePolicy)
        self.ET_label.setMinimumSize(QtCore.QSize(541, 0))
        self.ET_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                    "font: 25 22pt \"Bahnschrift Light\";")
        self.ET_label.setWordWrap(True)
        self.ET_label.setObjectName("ET_label")
        self.gridLayout_3.addWidget(self.ET_label, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addWidget(self.header_frame)
        self.student_portal_label_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_portal_label_frame.sizePolicy().hasHeightForWidth())
        self.student_portal_label_frame.setSizePolicy(sizePolicy)
        self.student_portal_label_frame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.student_portal_label_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.student_portal_label_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.student_portal_label_frame.setObjectName("student_portal_label_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.student_portal_label_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.welcome_label = QtWidgets.QLabel(self.student_portal_label_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_label.sizePolicy().hasHeightForWidth())
        self.welcome_label.setSizePolicy(sizePolicy)
        self.welcome_label.setMinimumSize(QtCore.QSize(900, 0))
        self.welcome_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                         "font:20pt \"Bahnschrift Light\";\n"
                                         "color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.0340909 rgba(0, 0, 255, 255), stop:0.204545 rgba(255, 255, 255, 255), stop:0.318182 rgba(0, 170, 0, 255), stop:0.522727 rgba(255, 255, 255, 255), stop:0.727273 rgba(0, 0, 255, 255), stop:0.926136 rgba(0, 170, 0, 255));\n"
                                         "")
        self.welcome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_label.setWordWrap(True)
        self.welcome_label.setObjectName("welcome_label")
        self.gridLayout_2.addWidget(self.welcome_label, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.student_portal_label_frame)
        self.main_body = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setMinimumSize(QtCore.QSize(0, 0))
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu_frame = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_menu_frame.sizePolicy().hasHeightForWidth())
        self.side_menu_frame.setSizePolicy(sizePolicy)
        self.side_menu_frame.setMinimumSize(QtCore.QSize(180, 0))
        self.side_menu_frame.setMaximumSize(QtCore.QSize(180, 16777215))
        self.side_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu_frame.setObjectName("side_menu_frame")
        self.dashboard_btn = QtWidgets.QPushButton(self.side_menu_frame)
        self.dashboard_btn.setGeometry(QtCore.QRect(10, 40, 150, 30))
        self.dashboard_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.dashboard_btn.setMaximumSize(QtCore.QSize(150, 100))
        self.dashboard_btn.setStyleSheet("background-image: url(:/icons/icons/white/home.svg);\n"
                                         "background-repeat:no-repeat;\n"
                                         "background-position:left;\n"
                                         "\n"
                                         "\n"
                                         "font: 12pt \"Bahnschrift SemiBold\";\n"
                                         "border: 1px solid green;\n"
                                         "background-color:  rgb(48, 78, 151);\n"
                                         "color: rgb(241, 241, 241);\n"
                                         "")
        self.dashboard_btn.setObjectName("dashboard_btn")
        self.my_profile_btn = QtWidgets.QPushButton(self.side_menu_frame)
        self.my_profile_btn.setGeometry(QtCore.QRect(10, 80, 150, 30))
        self.my_profile_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.my_profile_btn.setMaximumSize(QtCore.QSize(150, 100))
        self.my_profile_btn.setStyleSheet("background-repeat:no-repeat;\n"
                                          "background-position:left;\n"
                                          "background-image: url(:/icons/icons/white/user.svg);\n"
                                          "\n"
                                          "\n"
                                          "font: 12pt \"Bahnschrift SemiBold\";\n"
                                          "border: 1px solid green;\n"
                                          "background-color:  rgb(48, 78, 151);\n"
                                          "color: rgb(241, 241, 241);\n"
                                          "")
        self.my_profile_btn.setObjectName("my_profile_btn")
        self.courses_btn = QtWidgets.QPushButton(self.side_menu_frame)
        self.courses_btn.setGeometry(QtCore.QRect(10, 120, 150, 30))
        self.courses_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.courses_btn.setMaximumSize(QtCore.QSize(150, 100))
        self.courses_btn.setStyleSheet("background-repeat:no-repeat;\n"
                                       "background-position:left;\n"
                                       "background-image: url(:/icons/icons/white/book.svg);\n"
                                       "\n"
                                       "\n"
                                       "font: 12pt \"Bahnschrift SemiBold\";\n"
                                       "border: 1px solid green;\n"
                                       "background-color:  rgb(48, 78, 151);\n"
                                       "color: rgb(241, 241, 241);\n"
                                       "")
        self.courses_btn.setObjectName("courses_btn")
        self.test_results_btn = QtWidgets.QPushButton(self.side_menu_frame)
        self.test_results_btn.setGeometry(QtCore.QRect(10, 160, 150, 30))
        self.test_results_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.test_results_btn.setMaximumSize(QtCore.QSize(150, 100))
        self.test_results_btn.setStyleSheet("background-repeat:no-repeat;\n"
                                            "background-position:left;\n"
                                            "background-image: url(:/icons/icons/white/book-open.svg);\n"
                                            "\n"
                                            "\n"
                                            "font: 12pt \"Bahnschrift SemiBold\";\n"
                                            "border: 1px solid green;\n"
                                            "background-color:  rgb(48, 78, 151);\n"
                                            "color: rgb(241, 241, 241);\n"
                                            "")
        self.test_results_btn.setObjectName("test_results_btn")
        self.logout_btn = QtWidgets.QPushButton(self.side_menu_frame)
        self.logout_btn.setGeometry(QtCore.QRect(10, 240, 150, 30))
        self.logout_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.logout_btn.setMaximumSize(QtCore.QSize(150, 100))
        self.logout_btn.setStyleSheet("background-repeat:no-repeat;\n"
                                      "background-position:left;\n"
                                      "background-image: url(:/icons/icons/white/log-out.svg);\n"
                                      "\n"
                                      "\n"
                                      "font: 12pt \"Bahnschrift SemiBold\";\n"
                                      "\n"
                                      "background-color: red;\n"
                                      "color: rgb(241, 241, 241);\n"
                                      "border-radius:10px;\n"
                                      "")
        self.logout_btn.setObjectName("logout_btn")
        self.Quiz_btn = QtWidgets.QPushButton(self.side_menu_frame)
        self.Quiz_btn.setGeometry(QtCore.QRect(10, 200, 150, 30))
        self.Quiz_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.Quiz_btn.setMaximumSize(QtCore.QSize(150, 100))
        self.Quiz_btn.setStyleSheet("background-repeat:no-repeat;\n"
                                    "background-position:left;\n"
                                    "background-image: url(:/icons/icons/white/edit.svg);\n"
                                    "\n"
                                    "\n"
                                    "font: 12pt \"Bahnschrift SemiBold\";\n"
                                    "border: 1px solid green;\n"
                                    "background-color:  rgb(48, 78, 151);\n"
                                    "color: rgb(241, 241, 241);\n"
                                    "")
        self.Quiz_btn.setObjectName("Quiz_btn")
        self.horizontalLayout.addWidget(self.side_menu_frame)
        self.main_body_frame = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body_frame.sizePolicy().hasHeightForWidth())
        self.main_body_frame.setSizePolicy(sizePolicy)
        self.main_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_frame.setObjectName("main_body_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.main_body_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_body_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard_page = QtWidgets.QWidget()
        self.dashboard_page.setStyleSheet(
            "background-image: url(:/icons/icons/backgrounds/RAAS_logo-removebg-preview.png);\n"
            "background-position:center;\n"
            "background-repeat:no-repeat;")
        self.dashboard_page.setObjectName("dashboard_page")
        self.stackedWidget.addWidget(self.dashboard_page)
        self.my_profile_page = QtWidgets.QWidget()
        self.my_profile_page.setObjectName("my_profile_page")
        self.layoutWidget = QtWidgets.QWidget(self.my_profile_page)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 681, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.std_info_gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.std_info_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.std_info_gridLayout.setObjectName("std_info_gridLayout")
        self.personal_info_heading_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personal_info_heading_label.sizePolicy().hasHeightForWidth())
        self.personal_info_heading_label.setSizePolicy(sizePolicy)
        self.personal_info_heading_label.setMinimumSize(QtCore.QSize(120, 0))
        self.personal_info_heading_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                                       "font: 20pt \"Bahnschrift SemiBold\";")
        self.personal_info_heading_label.setObjectName("personal_info_heading_label")
        self.std_info_gridLayout.addWidget(self.personal_info_heading_label, 0, 0, 1, 2)
        self.std_no_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.std_no_label.sizePolicy().hasHeightForWidth())
        self.std_no_label.setSizePolicy(sizePolicy)
        self.std_no_label.setMinimumSize(QtCore.QSize(0, 30))
        self.std_no_label.setStyleSheet("color: rgb(0, 0, 0);\n"
                                        "font: bold 14pt \"Bahnschrift SemiBold\";\n"
                                        "")
        self.std_no_label.setAlignment(QtCore.Qt.AlignCenter)
        self.std_no_label.setWordWrap(True)
        self.std_no_label.setObjectName("std_no_label")
        self.std_info_gridLayout.addWidget(self.std_no_label, 1, 0, 1, 1)
        self.disp_std_ID_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disp_std_ID_label.sizePolicy().hasHeightForWidth())
        self.disp_std_ID_label.setSizePolicy(sizePolicy)
        self.disp_std_ID_label.setMinimumSize(QtCore.QSize(0, 30))
        self.disp_std_ID_label.setStyleSheet("color: rgb(74, 74, 74);\n"
                                             "font: 14pt \"Bahnschrift SemiBold\";\n"
                                             "")
        self.disp_std_ID_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.disp_std_ID_label.setWordWrap(True)
        self.disp_std_ID_label.setObjectName("disp_std_ID_label")
        self.std_info_gridLayout.addWidget(self.disp_std_ID_label, 1, 1, 1, 1)
        self.std_name_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.std_name_label.sizePolicy().hasHeightForWidth())
        self.std_name_label.setSizePolicy(sizePolicy)
        self.std_name_label.setMinimumSize(QtCore.QSize(0, 30))
        self.std_name_label.setStyleSheet("color: rgb(0, 0, 0);\n"
                                          "font: bold 14pt \"Bahnschrift SemiBold\";\n"
                                          "")
        self.std_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.std_name_label.setWordWrap(True)
        self.std_name_label.setObjectName("std_name_label")
        self.std_info_gridLayout.addWidget(self.std_name_label, 2, 0, 1, 1)
        self.disp_std_name_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disp_std_name_label.sizePolicy().hasHeightForWidth())
        self.disp_std_name_label.setSizePolicy(sizePolicy)
        self.disp_std_name_label.setMinimumSize(QtCore.QSize(0, 30))
        self.disp_std_name_label.setStyleSheet("color: rgb(74, 74, 74);\n"
                                               "font: 14pt \"Bahnschrift SemiBold\";\n"
                                               "")
        self.disp_std_name_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.disp_std_name_label.setWordWrap(True)
        self.disp_std_name_label.setObjectName("disp_std_name_label")
        self.std_info_gridLayout.addWidget(self.disp_std_name_label, 2, 1, 1, 1)
        self.email_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_label.sizePolicy().hasHeightForWidth())
        self.email_label.setSizePolicy(sizePolicy)
        self.email_label.setMinimumSize(QtCore.QSize(0, 30))
        self.email_label.setStyleSheet("color: rgb(0, 0, 0);\n"
                                       "font: bold 14pt \"Bahnschrift SemiBold\";\n"
                                       "")
        self.email_label.setAlignment(QtCore.Qt.AlignCenter)
        self.email_label.setWordWrap(True)
        self.email_label.setObjectName("email_label")
        self.std_info_gridLayout.addWidget(self.email_label, 3, 0, 1, 1)
        self.disp_std_email_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disp_std_email_label.sizePolicy().hasHeightForWidth())
        self.disp_std_email_label.setSizePolicy(sizePolicy)
        self.disp_std_email_label.setMinimumSize(QtCore.QSize(0, 30))
        self.disp_std_email_label.setStyleSheet("color: rgb(74, 74, 74);\n"
                                                "font: 14pt \"Bahnschrift SemiBold\";\n"
                                                "")
        self.disp_std_email_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.disp_std_email_label.setWordWrap(True)
        self.disp_std_email_label.setObjectName("disp_std_email_label")
        self.std_info_gridLayout.addWidget(self.disp_std_email_label, 3, 1, 1, 1)
        self.contact_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contact_label.sizePolicy().hasHeightForWidth())
        self.contact_label.setSizePolicy(sizePolicy)
        self.contact_label.setMinimumSize(QtCore.QSize(0, 30))
        self.contact_label.setStyleSheet("color: rgb(0, 0, 0);\n"
                                         "font: bold 14pt \"Bahnschrift SemiBold\";\n"
                                         "")
        self.contact_label.setAlignment(QtCore.Qt.AlignCenter)
        self.contact_label.setWordWrap(True)
        self.contact_label.setObjectName("contact_label")
        self.std_info_gridLayout.addWidget(self.contact_label, 4, 0, 1, 1)
        self.disp_std_contact_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disp_std_contact_label.sizePolicy().hasHeightForWidth())
        self.disp_std_contact_label.setSizePolicy(sizePolicy)
        self.disp_std_contact_label.setMinimumSize(QtCore.QSize(0, 30))
        self.disp_std_contact_label.setStyleSheet("color: rgb(74, 74, 74);\n"
                                                  "font: 14pt \"Bahnschrift SemiBold\";\n"
                                                  "")
        self.disp_std_contact_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.disp_std_contact_label.setWordWrap(True)
        self.disp_std_contact_label.setObjectName("disp_std_contact_label")
        self.std_info_gridLayout.addWidget(self.disp_std_contact_label, 4, 1, 1, 1)
        self.update_profile_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.update_profile_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.update_profile_btn.setMaximumSize(QtCore.QSize(150, 40))
        self.update_profile_btn.setStyleSheet("background-repeat:no-repeat;\n"
                                              "background-position:left;\n"
                                              "background-image: url(:/icons/icons/white/upload.svg);\n"
                                              "\n"
                                              "\n"
                                              "font: 12pt \"Bahnschrift SemiBold\";\n"
                                              "\n"
                                              "background-color:#6fa844 ;\n"
                                              "color: white;\n"
                                              "border-radius:10px;\n"
                                              "")
        self.update_profile_btn.setObjectName("update_profile_btn")
        self.std_info_gridLayout.addWidget(self.update_profile_btn, 5, 0, 1, 2)
        self.stackedWidget.addWidget(self.my_profile_page)
        self.courses_page = QtWidgets.QWidget()
        self.courses_page.setObjectName("courses_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.courses_page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.courses_gridlayout = QtWidgets.QGridLayout()
        self.courses_gridlayout.setObjectName("courses_gridlayout")
        self.your_courses_head_label = QtWidgets.QLabel(self.courses_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.your_courses_head_label.sizePolicy().hasHeightForWidth())
        self.your_courses_head_label.setSizePolicy(sizePolicy)
        self.your_courses_head_label.setMinimumSize(QtCore.QSize(0, 30))
        self.your_courses_head_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                                   "font: bold 14pt \"Bahnschrift SemiBold\";\n"
                                                   "")
        self.your_courses_head_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.your_courses_head_label.setWordWrap(True)
        self.your_courses_head_label.setObjectName("your_courses_head_label")
        self.courses_gridlayout.addWidget(self.your_courses_head_label, 0, 0, 1, 1)
        self.courses_listView = QtWidgets.QListView(self.courses_page)
        self.courses_listView.setStyleSheet("font: 14pt \"Bahnschrift SemiBold\";")
        self.courses_listView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.courses_listView.setResizeMode(QtWidgets.QListView.Adjust)
        self.courses_listView.setUniformItemSizes(True)
        self.courses_listView.setWordWrap(True)
        self.courses_listView.setObjectName("courses_listView")
        self.courses_gridlayout.addWidget(self.courses_listView, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.courses_gridlayout)
        self.stackedWidget.addWidget(self.courses_page)
        self.test_results_page = QtWidgets.QWidget()
        self.test_results_page.setObjectName("test_results_page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.test_results_page)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.test_result_gridLayout = QtWidgets.QGridLayout()
        self.test_result_gridLayout.setObjectName("test_result_gridLayout")
        self.test_results_tableWidget = QtWidgets.QTableWidget(self.test_results_page)
        self.test_results_tableWidget.setStyleSheet("font: 12pt \"Bahnschrift SemiBold\";")
        self.test_results_tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test_results_tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.test_results_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.test_results_tableWidget.setAlternatingRowColors(True)
        self.test_results_tableWidget.setObjectName("test_results_tableWidget")
        self.test_results_tableWidget.setColumnCount(4)
        self.test_results_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.test_results_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_results_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_results_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_results_tableWidget.setHorizontalHeaderItem(3, item)
        self.test_results_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.test_results_tableWidget.horizontalHeader().setDefaultSectionSize(170)
        self.test_results_tableWidget.horizontalHeader().setMinimumSectionSize(70)
        self.test_results_tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.test_result_gridLayout.addWidget(self.test_results_tableWidget, 2, 0, 1, 1)
        self.show_std_enroll_courses_comboBox = QtWidgets.QComboBox(self.test_results_page)
        self.show_std_enroll_courses_comboBox.setStyleSheet("font: 12pt \"Bahnschrift SemiBold\";\n"
                                                            "border: 1px solid green;")
        self.show_std_enroll_courses_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.show_std_enroll_courses_comboBox.setObjectName("show_std_enroll_courses_comboBox")
        self.test_result_gridLayout.addWidget(self.show_std_enroll_courses_comboBox, 1, 0, 1, 1)
        self.select_course_heading_label = QtWidgets.QLabel(self.test_results_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_course_heading_label.sizePolicy().hasHeightForWidth())
        self.select_course_heading_label.setSizePolicy(sizePolicy)
        self.select_course_heading_label.setMinimumSize(QtCore.QSize(0, 30))
        self.select_course_heading_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                                       "font: bold 14pt \"Bahnschrift SemiBold\";\n"
                                                       "")
        self.select_course_heading_label.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.select_course_heading_label.setWordWrap(True)
        self.select_course_heading_label.setObjectName("select_course_heading_label")
        self.test_result_gridLayout.addWidget(self.select_course_heading_label, 0, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.test_result_gridLayout)
        self.stackedWidget.addWidget(self.test_results_page)
        self.quiz_page = QtWidgets.QWidget()
        self.quiz_page.setObjectName("quiz_page")
        self.unattempt_quiz_name_label = QtWidgets.QLabel(self.quiz_page)
        self.unattempt_quiz_name_label.setGeometry(QtCore.QRect(70, 100, 515, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unattempt_quiz_name_label.sizePolicy().hasHeightForWidth())
        self.unattempt_quiz_name_label.setSizePolicy(sizePolicy)
        self.unattempt_quiz_name_label.setMinimumSize(QtCore.QSize(515, 30))
        self.unattempt_quiz_name_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                                     "font: bold 14pt \"Bahnschrift SemiBold\";\n"
                                                     "")
        self.unattempt_quiz_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.unattempt_quiz_name_label.setWordWrap(True)
        self.unattempt_quiz_name_label.setObjectName("unattempt_quiz_name_label")
        self.start_course_quiz_btn = QtWidgets.QPushButton(self.quiz_page)
        self.start_course_quiz_btn.setGeometry(QtCore.QRect(260, 150, 121, 30))
        self.start_course_quiz_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.start_course_quiz_btn.setMaximumSize(QtCore.QSize(150, 100))
        self.start_course_quiz_btn.setStyleSheet("\n"
                                                 "\n"
                                                 "\n"
                                                 "font: 12pt \"Bahnschrift SemiBold\";\n"
                                                 "\n"
                                                 "background-color: #6fa844;\n"
                                                 "color: white;\n"
                                                 "border-radius:10px;\n"
                                                 "")
        self.start_course_quiz_btn.setObjectName("start_course_quiz_btn")
        self.stackedWidget.addWidget(self.quiz_page)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.main_body_frame)
        self.verticalLayout_3.addWidget(self.main_body)
        self.gridLayout_6.addWidget(self.main_frame, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.border_frame)
        StudentPortal.setCentralWidget(self.centralwidget)

        self.retranslateUi(StudentPortal)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(StudentPortal)

    def retranslateUi(self, StudentPortal):
        _translate = QtCore.QCoreApplication.translate
        StudentPortal.setWindowTitle(_translate("StudentPortal", "MainWindow"))
        self.RAAS_label.setText(_translate("StudentPortal", "RAAS"))
        self.ET_label.setText(_translate("StudentPortal", "INSTITUTE OF EMERGING TECHNOLOGIES"))
        self.welcome_label.setText(_translate("StudentPortal", "WELCOME TO STUDENT PORTAL"))
        self.dashboard_btn.setText(_translate("StudentPortal", "Dashboard"))
        self.my_profile_btn.setText(_translate("StudentPortal", "My Profile"))
        self.courses_btn.setText(_translate("StudentPortal", "Courses"))
        self.test_results_btn.setText(_translate("StudentPortal", "Test Results"))
        self.logout_btn.setText(_translate("StudentPortal", "Logout"))
        self.Quiz_btn.setText(_translate("StudentPortal", "Quiz "))
        self.personal_info_heading_label.setText(_translate("StudentPortal", "Personal Information:"))
        self.std_no_label.setText(_translate("StudentPortal", "Student No:"))
        self.disp_std_ID_label.setText(_translate("StudentPortal", "DMF101-21-001"))
        self.std_name_label.setText(_translate("StudentPortal", "Student Name:"))
        self.disp_std_name_label.setText(_translate("StudentPortal", "Javeria Hassan"))
        self.email_label.setText(_translate("StudentPortal", "Email:"))
        self.disp_std_email_label.setText(_translate("StudentPortal", "javeria.hassan77@gmail.com"))
        self.contact_label.setText(_translate("StudentPortal", "Contact:"))
        self.disp_std_contact_label.setText(_translate("StudentPortal", "0304-5690876"))
        self.update_profile_btn.setText(_translate("StudentPortal", "Update"))
        self.your_courses_head_label.setText(_translate("StudentPortal", "Your Courses:"))
        self.test_results_tableWidget.setSortingEnabled(True)
        item = self.test_results_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("StudentPortal", "Course ID"))
        item = self.test_results_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("StudentPortal", "Assessment Name"))
        item = self.test_results_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("StudentPortal", "Total Marks"))
        item = self.test_results_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("StudentPortal", "Obtained Marks"))
        self.select_course_heading_label.setText(_translate("StudentPortal", "Select Course"))
        self.unattempt_quiz_name_label.setText(_translate("StudentPortal", "Quiz 2 - Python"))
        self.start_course_quiz_btn.setText(_translate("StudentPortal", "Start Quiz"))


import icon_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    StudentPortal = QtWidgets.QMainWindow()
    ui = Ui_StudentPortal()
    ui.setupUi(StudentPortal)
    StudentPortal.show()
    sys.exit(app.exec_())
