# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1024, 644)
        Login.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/backgrounds/hands.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        Login.setStyleSheet("QFrame#login_form{\n"
"background-color: rgb(48, 78, 151);\n"
"border-radius:40px;\n"
"margin: 60px;\n"
"}\n"
"QFrame#border_frame\n"
"{\n"
"background-color:#6fa844 ;\n"
"}\n"
"QFrame#main_frame{\n"
"background-image: url(:/icons/Background2.jpg);\n"
"\n"
"background-position:center;\n"
"background-repeat:no-repeat;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.border_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_frame.sizePolicy().hasHeightForWidth())
        self.border_frame.setSizePolicy(sizePolicy)
        self.border_frame.setStyleSheet("")
        self.border_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_frame.setObjectName("border_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.border_frame)
        self.verticalLayout_2.setContentsMargins(80, 80, 80, 80)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_frame = QtWidgets.QFrame(self.border_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_frame.setStyleSheet("")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.heading_side_bar = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heading_side_bar.sizePolicy().hasHeightForWidth())
        self.heading_side_bar.setSizePolicy(sizePolicy)
        self.heading_side_bar.setMinimumSize(QtCore.QSize(240, 0))
        self.heading_side_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.heading_side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.heading_side_bar.setLineWidth(0)
        self.heading_side_bar.setObjectName("heading_side_bar")
        self.RAAS_label = QtWidgets.QLabel(self.heading_side_bar)
        self.RAAS_label.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.RAAS_label.setStyleSheet("color: rgb(48, 78, 151);\n"
"font: 63 32pt \"Bahnschrift SemiBold\";")
        self.RAAS_label.setObjectName("RAAS_label")
        self.ET_label = QtWidgets.QLabel(self.heading_side_bar)
        self.ET_label.setGeometry(QtCore.QRect(10, 60, 221, 101))
        self.ET_label.setStyleSheet("color: rgb(48, 78, 151);\n"
"font: 25 22pt \"Bahnschrift Light\";")
        self.ET_label.setWordWrap(True)
        self.ET_label.setObjectName("ET_label")
        self.horizontalLayout.addWidget(self.heading_side_bar)
        self.login_form = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_form.sizePolicy().hasHeightForWidth())
        self.login_form.setSizePolicy(sizePolicy)
        self.login_form.setMinimumSize(QtCore.QSize(470, 480))
        self.login_form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.login_form.setStyleSheet("")
        self.login_form.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_form.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.login_form.setLineWidth(0)
        self.login_form.setObjectName("login_form")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.login_form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.login_grid_layout = QtWidgets.QGridLayout()
        self.login_grid_layout.setVerticalSpacing(10)
        self.login_grid_layout.setObjectName("login_grid_layout")
        self.test_portal_heading = QtWidgets.QLabel(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_portal_heading.sizePolicy().hasHeightForWidth())
        self.test_portal_heading.setSizePolicy(sizePolicy)
        self.test_portal_heading.setStyleSheet("color: rgb(241, 241, 241);\n"
"\n"
"font: 25 18pt \"Bahnschrift Light Condensed\";\n"
"margin:5px;")
        self.test_portal_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.test_portal_heading.setObjectName("test_portal_heading")
        self.login_grid_layout.addWidget(self.test_portal_heading, 1, 0, 1, 1)
        self.ID_underline = QtWidgets.QLineEdit(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ID_underline.sizePolicy().hasHeightForWidth())
        self.ID_underline.setSizePolicy(sizePolicy)
        self.ID_underline.setMinimumSize(QtCore.QSize(240, 0))
        self.ID_underline.setMaximumSize(QtCore.QSize(240, 1))
        self.ID_underline.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 25 12pt \"Bahnschrift Light\";\n"
"margin:0px;\n"
"border: 1px solid white;")
        self.ID_underline.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ID_underline.setPlaceholderText("")
        self.ID_underline.setObjectName("ID_underline")
        self.login_grid_layout.addWidget(self.ID_underline, 3, 0, 1, 1)
        self.user_login_heading = QtWidgets.QLabel(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_login_heading.sizePolicy().hasHeightForWidth())
        self.user_login_heading.setSizePolicy(sizePolicy)
        self.user_login_heading.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 63 20pt \"Bahnschrift SemiBold\";\n"
"margin:5px;")
        self.user_login_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.user_login_heading.setObjectName("user_login_heading")
        self.login_grid_layout.addWidget(self.user_login_heading, 0, 0, 1, 1)
        self.ID_lineEdit = QtWidgets.QLineEdit(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ID_lineEdit.sizePolicy().hasHeightForWidth())
        self.ID_lineEdit.setSizePolicy(sizePolicy)
        self.ID_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.ID_lineEdit.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 25 12pt \"Bahnschrift Light\";\n"
"margin:5px;\n"
"background-color: rgb(48, 78, 151 0.73);\n"
"border:0px;\n"
"")
        self.ID_lineEdit.setObjectName("ID_lineEdit")
        self.login_grid_layout.addWidget(self.ID_lineEdit, 2, 0, 1, 1)
        self.login_btn = QtWidgets.QPushButton(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMinimumSize(QtCore.QSize(250, 40))
        self.login_btn.setMaximumSize(QtCore.QSize(100, 40))
        self.login_btn.setStyleSheet("background-color: rgb(111, 168, 68);\n"
"border-radius: 15px;\n"
"color: rgb(241, 241, 241);\n"
"font:  bold 10pt \"Bahnschrift Light\";margin:5px;\n"
"vertical-align: center;\n"
"horizontal-align: center;")
        self.login_btn.setAutoDefault(False)
        self.login_btn.setFlat(False)
        self.login_btn.setObjectName("login_btn")
        self.login_grid_layout.addWidget(self.login_btn, 6, 0, 1, 1)
        self.password_line_edit = QtWidgets.QLineEdit(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_line_edit.sizePolicy().hasHeightForWidth())
        self.password_line_edit.setSizePolicy(sizePolicy)
        self.password_line_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.password_line_edit.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 25 12pt \"Bahnschrift Light\";\n"
"margin:5px;\n"
"background-color: rgb(48, 78, 151 0.73);\n"
"border:0px;")
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line_edit.setObjectName("password_line_edit")
        self.login_grid_layout.addWidget(self.password_line_edit, 4, 0, 1, 1)
        self.error_label = QtWidgets.QLabel(self.login_form)
        self.error_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_label.sizePolicy().hasHeightForWidth())
        self.error_label.setSizePolicy(sizePolicy)
        self.error_label.setMinimumSize(QtCore.QSize(250, 0))
        self.error_label.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 25 12pt \"Bahnschrift Light\";\n"
"margin:5px;")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.login_grid_layout.addWidget(self.error_label, 7, 0, 1, 1)
        self.password_underline = QtWidgets.QLineEdit(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_underline.sizePolicy().hasHeightForWidth())
        self.password_underline.setSizePolicy(sizePolicy)
        self.password_underline.setMinimumSize(QtCore.QSize(240, 0))
        self.password_underline.setMaximumSize(QtCore.QSize(240, 1))
        self.password_underline.setStyleSheet("color: rgb(241, 241, 241);\n"
"font: 25 12pt \"Bahnschrift Light\";\n"
"margin:0px;\n"
"border: 1px solid white;")
        self.password_underline.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_underline.setPlaceholderText("")
        self.password_underline.setObjectName("password_underline")
        self.login_grid_layout.addWidget(self.password_underline, 5, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.login_grid_layout)
        self.horizontalLayout.addWidget(self.login_form, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.logo_side_bar = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_side_bar.sizePolicy().hasHeightForWidth())
        self.logo_side_bar.setSizePolicy(sizePolicy)
        self.logo_side_bar.setMinimumSize(QtCore.QSize(150, 0))
        self.logo_side_bar.setStyleSheet("")
        self.logo_side_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_side_bar.setLineWidth(0)
        self.logo_side_bar.setObjectName("logo_side_bar")
        self.gridLayout = QtWidgets.QGridLayout(self.logo_side_bar)
        self.gridLayout.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.hunar_logo = QtWidgets.QLabel(self.logo_side_bar)
        self.hunar_logo.setMinimumSize(QtCore.QSize(80, 120))
        self.hunar_logo.setMaximumSize(QtCore.QSize(80, 120))
        self.hunar_logo.setStyleSheet("background-image: url(:/icons/icons/backgrounds/Asset 7-100.jpg);\n"
"background-repeat: no-repeat; \n"
" background-position: right;\n"
"margin:5px;\n"
"")
        self.hunar_logo.setText("")
        self.hunar_logo.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.hunar_logo.setObjectName("hunar_logo")
        self.gridLayout.addWidget(self.hunar_logo, 0, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.logo_side_bar)
        self.verticalLayout_2.addWidget(self.main_frame)
        self.verticalLayout.addWidget(self.border_frame)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.RAAS_label.setText(_translate("Login", "RAAS"))
        self.ET_label.setText(_translate("Login", "INSTITUTE OF EMERGING TECHNOLOGIES"))
        self.test_portal_heading.setText(_translate("Login", "Welcome to the Test Portal"))
        self.user_login_heading.setText(_translate("Login", "USER LOGIN"))
        self.ID_lineEdit.setPlaceholderText(_translate("Login", "ID"))
        self.login_btn.setText(_translate("Login", "LOGIN"))
        self.password_line_edit.setPlaceholderText(_translate("Login", "Password"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
