# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_question.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddQuestionWindow(object):
    def setupUi(self, AddQeustionWindow):
        AddQeustionWindow.setObjectName("AddQuestionWindow")
        AddQeustionWindow.resize(1052, 568)
        AddQeustionWindow.setStyleSheet("QFrame#login_form{\n"
                                        "background-color: rgb(48, 78, 151);\n"
                                        "border-radius:40px;\n"
                                        "margin: 60px;\n"
                                        "}\n"
                                        "QFrame#border_frame\n"
                                        "{\n"
                                        "background-color:#6fa844 ;\n"
                                        "}\n"
                                        "QFrame#main_frame{\n"
                                        "background-image: url(:/icons/Background2.jpg);\n"
                                        "\n"
                                        "background-position:center;\n"
                                        "background-repeat:no-repeat;\n"
                                        "}\n"
                                        "QComboBox#search_filter_comboBox::down-arrow\n"
                                        "{\n"
                                        "color :green;\n"
                                        "}\n"
                                        "QPushButton::ToolTip\n"
                                        "{\n"
                                        "background-color: white;\n"
                                        "color:black;\n"
                                        "background-image:none;\n"
                                        "}\n"
                                        "QTabWidget{background: gray;}")
        self.centralwidget = QtWidgets.QWidget(AddQeustionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.border_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_frame.sizePolicy().hasHeightForWidth())
        self.border_frame.setSizePolicy(sizePolicy)
        self.border_frame.setStyleSheet("")
        self.border_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_frame.setObjectName("border_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.border_frame)
        self.gridLayout_6.setContentsMargins(40, 40, 40, 40)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.main_frame = QtWidgets.QFrame(self.border_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_frame.setStyleSheet("")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 120))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.header_frame.setStyleSheet("")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.header_gridLayout = QtWidgets.QGridLayout()
        self.header_gridLayout.setSpacing(0)
        self.header_gridLayout.setObjectName("header_gridLayout")
        self.hunar_logo = QtWidgets.QLabel(self.header_frame)
        self.hunar_logo.setMinimumSize(QtCore.QSize(70, 100))
        self.hunar_logo.setMaximumSize(QtCore.QSize(70, 100))
        self.hunar_logo.setStyleSheet("\n"
                                      "background-image: url(:/icons/icons/backgrounds/Asset 7-100.jpg);\n"
                                      "background-repeat: no-repeat; \n"
                                      " background-position: right;\n"
                                      "margin:5px;\n"
                                      "")
        self.hunar_logo.setText("")
        self.hunar_logo.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing)
        self.hunar_logo.setObjectName("hunar_logo")
        self.header_gridLayout.addWidget(self.hunar_logo, 0, 0, 2, 1)
        self.ET_label = QtWidgets.QLabel(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ET_label.sizePolicy().hasHeightForWidth())
        self.ET_label.setSizePolicy(sizePolicy)
        self.ET_label.setMinimumSize(QtCore.QSize(541, 0))
        self.ET_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                    "font: 25 22pt \"Bahnschrift Light\";")
        self.ET_label.setWordWrap(True)
        self.ET_label.setObjectName("ET_label")
        self.header_gridLayout.addWidget(self.ET_label, 1, 1, 1, 1)
        self.RAAS_label = QtWidgets.QLabel(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAAS_label.sizePolicy().hasHeightForWidth())
        self.RAAS_label.setSizePolicy(sizePolicy)
        self.RAAS_label.setMinimumSize(QtCore.QSize(120, 0))
        self.RAAS_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                      "font: 63 32pt \"Bahnschrift SemiBold\";")
        self.RAAS_label.setObjectName("RAAS_label")
        self.header_gridLayout.addWidget(self.RAAS_label, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.header_gridLayout)
        self.verticalLayout_3.addWidget(self.header_frame)
        self.main_body = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setMinimumSize(QtCore.QSize(0, 0))
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.main_body)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Name_Label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Name_Label.setFont(font)
        self.Name_Label.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                      "color: rgb(0, 0, 0);")
        self.Name_Label.setObjectName("Name_Label")
        self.gridLayout.addWidget(self.Name_Label, 0, 0, 1, 1)
        self.question_text_edit = QtWidgets.QTextEdit(self.groupBox)
        self.question_text_edit.setMaximumSize(QtCore.QSize(16777215, 300))
        self.question_text_edit.setStyleSheet("color: rgb(74, 74, 74);\n"
                                              "font: 12pt\"Bahnschrift Light\";")
        self.question_text_edit.setObjectName("question_text_edit")
        self.gridLayout.addWidget(self.question_text_edit, 0, 1, 1, 5)
        self.q_img_path_label = QtWidgets.QLabel(self.groupBox)
        self.q_img_path_label.setMaximumSize(QtCore.QSize(16777215, 300))
        self.q_img_path_label.setStyleSheet("font: 8pt\"Bahnschrift Light\";")
        self.q_img_path_label.setObjectName("q_img_path_label")
        self.gridLayout.addWidget(self.q_img_path_label, 0, 6, 1, 3)
        self.q_img_btn = QtWidgets.QPushButton(self.groupBox)
        self.q_img_btn.setStyleSheet("background-color: rgb(12, 164, 84);\n"
                                     "background-image: url(:/Icons/icons/white/folder.svg);\n"
                                     "font: 12pt\"Bahnschrift Light\";\n"
                                     "border-color: rgb(5, 74, 162);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "background-position: left;\n"
                                     "background-repeat: no-repeat;")
        self.q_img_btn.setObjectName("q_img_btn")
        self.gridLayout.addWidget(self.q_img_btn, 0, 9, 1, 1)
        self.opt1_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.opt1_label.setFont(font)
        self.opt1_label.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                      "color: rgb(0, 0, 0);")
        self.opt1_label.setObjectName("opt1_label")
        self.gridLayout.addWidget(self.opt1_label, 1, 0, 1, 1)
        self.option1_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.option1_lineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.option1_lineEdit.setStyleSheet("color: rgb(74, 74, 74);\n"
                                            "font: 12pt\"Bahnschrift Light\";")
        self.option1_lineEdit.setObjectName("option1_lineEdit")
        self.gridLayout.addWidget(self.option1_lineEdit, 1, 1, 1, 5)
        self.opt1img_path_label = QtWidgets.QLabel(self.groupBox)
        self.opt1img_path_label.setStyleSheet("font: 8pt\"Bahnschrift Light\";")
        self.opt1img_path_label.setObjectName("opt1img_path_label")
        self.gridLayout.addWidget(self.opt1img_path_label, 1, 6, 1, 3)
        self.opt1_img_btn = QtWidgets.QPushButton(self.groupBox)
        self.opt1_img_btn.setStyleSheet("background-color: rgb(12, 164, 84);\n"
                                        "background-image: url(:/Icons/icons/white/folder.svg);\n"
                                        "font: 12pt\"Bahnschrift Light\";\n"
                                        "border-color: rgb(5, 74, 162);\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-position: left;\n"
                                        "background-repeat: no-repeat;")
        self.opt1_img_btn.setObjectName("opt1_img_btn")
        self.gridLayout.addWidget(self.opt1_img_btn, 1, 9, 1, 1)
        self.opt2_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.opt2_label.setFont(font)
        self.opt2_label.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                      "color: rgb(0, 0, 0);")
        self.opt2_label.setObjectName("opt2_label")
        self.gridLayout.addWidget(self.opt2_label, 2, 0, 1, 1)
        self.option2_line_edit = QtWidgets.QLineEdit(self.groupBox)
        self.option2_line_edit.setMinimumSize(QtCore.QSize(0, 24))
        self.option2_line_edit.setStyleSheet("color: rgb(74, 74, 74);\n"
                                             "font: 12pt\"Bahnschrift Light\";")
        self.option2_line_edit.setObjectName("option2_line_edit")
        self.gridLayout.addWidget(self.option2_line_edit, 2, 1, 1, 5)
        self.opt2_img_path_label = QtWidgets.QLabel(self.groupBox)
        self.opt2_img_path_label.setStyleSheet("font: 8pt\"Bahnschrift Light\";")
        self.opt2_img_path_label.setObjectName("opt2_img_path_label")
        self.gridLayout.addWidget(self.opt2_img_path_label, 2, 6, 1, 3)
        self.opt2_img_btn = QtWidgets.QPushButton(self.groupBox)
        self.opt2_img_btn.setStyleSheet("background-color: rgb(12, 164, 84);\n"
                                        "background-image: url(:/Icons/icons/white/folder.svg);\n"
                                        "font: 12pt\"Bahnschrift Light\";\n"
                                        "border-color: rgb(5, 74, 162);\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-position: left;\n"
                                        "background-repeat: no-repeat;")
        self.opt2_img_btn.setObjectName("opt2_img_btn")
        self.gridLayout.addWidget(self.opt2_img_btn, 2, 9, 1, 1)
        self.opt3_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.opt3_label.setFont(font)
        self.opt3_label.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                      "color: rgb(0, 0, 0);")
        self.opt3_label.setObjectName("opt3_label")
        self.gridLayout.addWidget(self.opt3_label, 3, 0, 1, 1)
        self.option3_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.option3_lineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.option3_lineEdit.setStyleSheet("color: rgb(74, 74, 74);\n"
                                            "font: 12pt\"Bahnschrift Light\";")
        self.option3_lineEdit.setObjectName("option3_lineEdit")
        self.gridLayout.addWidget(self.option3_lineEdit, 3, 1, 1, 5)
        self.opt3_img_path_label = QtWidgets.QLabel(self.groupBox)
        self.opt3_img_path_label.setStyleSheet("font: 8pt\"Bahnschrift Light\";")
        self.opt3_img_path_label.setObjectName("opt3_img_path_label")
        self.gridLayout.addWidget(self.opt3_img_path_label, 3, 6, 1, 3)
        self.opt3_img_btn = QtWidgets.QPushButton(self.groupBox)
        self.opt3_img_btn.setStyleSheet("background-color: rgb(12, 164, 84);\n"
                                        "background-image: url(:/Icons/icons/white/folder.svg);\n"
                                        "font: 12pt\"Bahnschrift Light\";\n"
                                        "border-color: rgb(5, 74, 162);\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-position: left;\n"
                                        "background-repeat: no-repeat;")
        self.opt3_img_btn.setObjectName("opt3_img_btn")
        self.gridLayout.addWidget(self.opt3_img_btn, 3, 9, 1, 1)
        self.opt4_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.opt4_label.setFont(font)
        self.opt4_label.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                      "color: rgb(0, 0, 0);")
        self.opt4_label.setObjectName("opt4_label")
        self.gridLayout.addWidget(self.opt4_label, 4, 0, 1, 1)
        self.option4_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.option4_lineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.option4_lineEdit.setStyleSheet("color: rgb(74, 74, 74);\n"
                                            "font: 12pt\"Bahnschrift Light\";")
        self.option4_lineEdit.setObjectName("option4_lineEdit")
        self.gridLayout.addWidget(self.option4_lineEdit, 4, 1, 1, 5)
        self.opt4_img_path_label = QtWidgets.QLabel(self.groupBox)
        self.opt4_img_path_label.setStyleSheet("font: 8pt\"Bahnschrift Light\";")
        self.opt4_img_path_label.setObjectName("opt4_img_path_label")
        self.gridLayout.addWidget(self.opt4_img_path_label, 4, 6, 1, 3)
        self.opt4_img_btn = QtWidgets.QPushButton(self.groupBox)
        self.opt4_img_btn.setStyleSheet("background-color: rgb(12, 164, 84);\n"
                                        "background-image: url(:/Icons/icons/white/folder.svg);\n"
                                        "font: 12pt\"Bahnschrift Light\";\n"
                                        "border-color: rgb(5, 74, 162);\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-position: left;\n"
                                        "background-repeat: no-repeat;")
        self.opt4_img_btn.setObjectName("opt4_img_btn")
        self.gridLayout.addWidget(self.opt4_img_btn, 4, 9, 1, 1)
        self.right_ans_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.right_ans_label.setFont(font)
        self.right_ans_label.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                           "color: rgb(0, 0, 0);")
        self.right_ans_label.setObjectName("right_ans_label")
        self.gridLayout.addWidget(self.right_ans_label, 5, 0, 1, 2)
        self.opt1_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.opt1_radioButton.setStyleSheet("font: 11pt\"Bahnschrift Light\";")
        self.opt1_radioButton.setObjectName("opt1_radioButton")
        self.gridLayout.addWidget(self.opt1_radioButton, 5, 2, 1, 1)
        self.opt2_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.opt2_radioButton.setStyleSheet("font: 11pt\"Bahnschrift Light\";")
        self.opt2_radioButton.setObjectName("opt2_radioButton")
        self.gridLayout.addWidget(self.opt2_radioButton, 5, 3, 1, 1)
        self.opt3_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.opt3_radioButton.setStyleSheet("font: 11pt\"Bahnschrift Light\";")
        self.opt3_radioButton.setObjectName("opt3_radioButton")
        self.gridLayout.addWidget(self.opt3_radioButton, 5, 4, 1, 1)
        self.opt4_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.opt4_radioButton.setStyleSheet("font: 11pt\"Bahnschrift Light\";")
        self.opt4_radioButton.setObjectName("opt4_radioButton")
        self.gridLayout.addWidget(self.opt4_radioButton, 5, 5, 1, 1)
        self.right_ans_img_path_label = QtWidgets.QLabel(self.groupBox)
        self.right_ans_img_path_label.setStyleSheet("font: 8pt\"Bahnschrift Light\";")
        self.right_ans_img_path_label.setObjectName("right_ans_img_path_label")
        self.gridLayout.addWidget(self.right_ans_img_path_label, 5, 6, 1, 3)
        self.right_ans_img_btn = QtWidgets.QPushButton(self.groupBox)
        self.right_ans_img_btn.setStyleSheet("background-color: rgb(12, 164, 84);\n"
                                             "background-image: url(:/Icons/icons/white/folder.svg);\n"
                                             "font: 12pt\"Bahnschrift Light\";\n"
                                             "border-color: rgb(5, 74, 162);\n"
                                             "color: rgb(255, 255, 255);\n"
                                             "background-position: left;\n"
                                             "background-repeat: no-repeat;")
        self.right_ans_img_btn.setObjectName("right_ans_img_btn")
        self.gridLayout.addWidget(self.right_ans_img_btn, 5, 9, 1, 1)
        self.marks_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.marks_label.setFont(font)
        self.marks_label.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                       "color: rgb(0, 0, 0);")
        self.marks_label.setObjectName("marks_label")
        self.gridLayout.addWidget(self.marks_label, 6, 0, 1, 1)
        self.q_marks_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.q_marks_spinBox.setStyleSheet("color: rgb(74, 74, 74);\n"
                                           "font: 12pt\"Bahnschrift Light\";")
        self.q_marks_spinBox.setMinimum(1)
        self.q_marks_spinBox.setObjectName("q_marks_spinBox")
        self.gridLayout.addWidget(self.q_marks_spinBox, 6, 1, 1, 5)
        self.q_section_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.q_section_label.setFont(font)
        self.q_section_label.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                           "color: rgb(0, 0, 0);")
        self.q_section_label.setObjectName("q_section_label")
        self.gridLayout.addWidget(self.q_section_label, 6, 6, 1, 1)
        self.q_section_combo_box = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_section_combo_box.sizePolicy().hasHeightForWidth())
        self.q_section_combo_box.setSizePolicy(sizePolicy)
        self.q_section_combo_box.setMaximumSize(QtCore.QSize(800, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.q_section_combo_box.setFont(font)
        self.q_section_combo_box.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                               "background-color: rgb(255, 255, 255);")
        self.q_section_combo_box.setCurrentText("")
        self.q_section_combo_box.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.q_section_combo_box.setObjectName("q_section_combo_box")
        self.gridLayout.addWidget(self.q_section_combo_box, 6, 7, 1, 3)
        self.status_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.status_label.setFont(font)
        self.status_label.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                        "color: rgb(0, 0, 0);")
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 7, 0, 1, 1)
        self.q_status_combo_box = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_status_combo_box.sizePolicy().hasHeightForWidth())
        self.q_status_combo_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.q_status_combo_box.setFont(font)
        self.q_status_combo_box.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                              "background-color: rgb(255, 255, 255);")
        self.q_status_combo_box.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.q_status_combo_box.setObjectName("q_status_combo_box")
        self.q_status_combo_box.addItem("")
        self.q_status_combo_box.addItem("")
        self.gridLayout.addWidget(self.q_status_combo_box, 7, 1, 1, 4)
        self.add_question_btn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_question_btn.sizePolicy().hasHeightForWidth())
        self.add_question_btn.setSizePolicy(sizePolicy)
        self.add_question_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.add_question_btn.setStyleSheet("background-color: rgb(5, 74, 162);\n"
                                            "\n"
                                            "font: 12pt\"Bahnschrift Light\";\n"
                                            "border-color: rgb(5, 74, 162);\n"
                                            "color: rgb(255, 255, 255);\n"
                                            "background-position: left;\n"
                                            "background-repeat: no-repeat;")
        self.add_question_btn.setObjectName("add_question_btn")
        self.gridLayout.addWidget(self.add_question_btn, 7, 5, 1, 3)
        self.dis_error_msg = QtWidgets.QLabel(self.groupBox)
        self.dis_error_msg.setStyleSheet("font: 12pt\"Bahnschrift Light\";\n"
                                         "color: rgb(255, 0, 0);")
        self.dis_error_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.dis_error_msg.setObjectName("dis_error_msg")
        self.gridLayout.addWidget(self.dis_error_msg, 7, 8, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_3.addWidget(self.main_body)
        self.gridLayout_6.addWidget(self.main_frame, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.border_frame)
        AddQeustionWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddQeustionWindow)
        QtCore.QMetaObject.connectSlotsByName(AddQeustionWindow)

    def retranslateUi(self, AddQeustionWindow):
        _translate = QtCore.QCoreApplication.translate
        AddQeustionWindow.setWindowTitle(_translate("AddQeustionWindow", "MainWindow"))
        self.ET_label.setText(_translate("AddQeustionWindow", "INSTITUTE OF EMERGING TECHNOLOGIES"))
        self.RAAS_label.setText(_translate("AddQeustionWindow", "RAAS"))
        self.Name_Label.setText(_translate("AddQeustionWindow", "Question"))
        self.question_text_edit.setPlaceholderText(_translate("AddQeustionWindow", "Type Question here..."))
        self.q_img_path_label.setText(_translate("AddQeustionWindow", "Choose Question Image (if Any)"))
        self.q_img_btn.setText(_translate("AddQeustionWindow", "Browse Question Image"))
        self.opt1_label.setText(_translate("AddQeustionWindow", "Option 1"))
        self.opt1img_path_label.setText(_translate("AddQeustionWindow", "Choose  Image for Option 1 (if Any)"))
        self.opt1_img_btn.setText(_translate("AddQeustionWindow", "Browse Option 1 Image"))
        self.opt2_label.setText(_translate("AddQeustionWindow", "Option 2"))
        self.opt2_img_path_label.setText(_translate("AddQeustionWindow", "Choose  Image for Option 2 (if Any)"))
        self.opt2_img_btn.setText(_translate("AddQeustionWindow", "Browse Option 2 Image"))
        self.opt3_label.setText(_translate("AddQeustionWindow", "Option 3"))
        self.opt3_img_path_label.setText(_translate("AddQeustionWindow", "Choose  Image for Option 3 (if Any)"))
        self.opt3_img_btn.setText(_translate("AddQeustionWindow", "Browse Option 3 Image"))
        self.opt4_label.setText(_translate("AddQeustionWindow", "Option 4"))
        self.opt4_img_path_label.setText(_translate("AddQeustionWindow", "Choose  Image for Option 4 (if Any)"))
        self.opt4_img_btn.setText(_translate("AddQeustionWindow", "BrowseOption 4 Image"))
        self.right_ans_label.setText(_translate("AddQeustionWindow", "Choose Right Answer"))
        self.opt1_radioButton.setText(_translate("AddQeustionWindow", "Option 1"))
        self.opt2_radioButton.setText(_translate("AddQeustionWindow", "Option 2"))
        self.opt3_radioButton.setText(_translate("AddQeustionWindow", "Option 3"))
        self.opt4_radioButton.setText(_translate("AddQeustionWindow", "Option 4"))
        self.right_ans_img_path_label.setText(
            _translate("AddQeustionWindow", "Choose  Image for right answer (if Any)"))
        self.right_ans_img_btn.setText(_translate("AddQeustionWindow", "Browse Right Answer Image"))
        self.marks_label.setText(_translate("AddQeustionWindow", "Marks"))
        self.q_section_label.setText(_translate("AddQeustionWindow", "Section"))
        self.status_label.setText(_translate("AddQeustionWindow", "Status"))
        self.q_status_combo_box.setCurrentText(_translate("AddQeustionWindow", "Active"))
        self.q_status_combo_box.setItemText(0, _translate("AddQeustionWindow", "Active"))
        self.q_status_combo_box.setItemText(1, _translate("AddQeustionWindow", "De-active"))
        self.add_question_btn.setText(_translate("AddQeustionWindow", "Add Question"))
        self.dis_error_msg.setText(_translate("AddQeustionWindow", "Please fill all required fields"))


import icon_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    AddQeustionWindow = QtWidgets.QMainWindow()
    ui = Ui_AddQuestionWindow()
    ui.setupUi(AddQeustionWindow)
    AddQeustionWindow.show()
    sys.exit(app.exec_())
