# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import icon_rc


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 662)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/backgrounds/hands.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QFrame#login_form{\n"
                                 "background-color: rgb(48, 78, 151);\n"
                                 "border-radius:40px;\n"
                                 "margin: 60px;\n"
                                 "}\n"
                                 "QFrame#border_frame\n"
                                 "{\n"
                                 "background-color:#6fa844 ;\n"
                                 "}\n"
                                 "QFrame#main_frame{\n"
                                 "background-image: url(:/icons/Background2.jpg);\n"
                                 "\n"
                                 "background-position:center;\n"
                                 "background-repeat:no-repeat;\n"
                                 "}\n"
                                 "QCheckBox#remember_me_checkbox::indicator:checked:pressed\n"
                                 "{\n"
                                 "background-color : green;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.border_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_frame.sizePolicy().hasHeightForWidth())
        self.border_frame.setSizePolicy(sizePolicy)
        self.border_frame.setStyleSheet("")
        self.border_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_frame.setObjectName("border_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.border_frame)
        self.verticalLayout_2.setContentsMargins(80, 80, 80, 80)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_frame = QtWidgets.QFrame(self.border_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_frame.setStyleSheet("")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.heading_side_bar = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heading_side_bar.sizePolicy().hasHeightForWidth())
        self.heading_side_bar.setSizePolicy(sizePolicy)
        self.heading_side_bar.setMinimumSize(QtCore.QSize(240, 0))
        self.heading_side_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.heading_side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.heading_side_bar.setLineWidth(0)
        self.heading_side_bar.setObjectName("heading_side_bar")
        self.RAAS_heading_label = QtWidgets.QLabel(self.heading_side_bar)
        self.RAAS_heading_label.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.RAAS_heading_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                              "font: 63 32pt \"Bahnschrift SemiBold\";")
        self.RAAS_heading_label.setObjectName("RAAS_heading_label")
        self.ET_label = QtWidgets.QLabel(self.heading_side_bar)
        self.ET_label.setGeometry(QtCore.QRect(10, 60, 221, 101))
        self.ET_label.setStyleSheet("color: rgb(48, 78, 151);\n"
                                    "font: 25 22pt \"Bahnschrift Light\";")
        self.ET_label.setWordWrap(True)
        self.ET_label.setObjectName("ET_label")
        self.horizontalLayout.addWidget(self.heading_side_bar)
        self.login_form = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_form.sizePolicy().hasHeightForWidth())
        self.login_form.setSizePolicy(sizePolicy)
        self.login_form.setMinimumSize(QtCore.QSize(470, 480))
        self.login_form.setMaximumSize(QtCore.QSize(16777215, 800))
        self.login_form.setStyleSheet("")
        self.login_form.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_form.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.login_form.setLineWidth(0)
        self.login_form.setObjectName("login_form")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.login_form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logingrid_layout = QtWidgets.QGridLayout()
        self.logingrid_layout.setObjectName("logingrid_layout")
        self.user_login_heading = QtWidgets.QLabel(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_login_heading.sizePolicy().hasHeightForWidth())
        self.user_login_heading.setSizePolicy(sizePolicy)
        self.user_login_heading.setStyleSheet("color: rgb(241, 241, 241);\n"
                                              "font: 63 20pt \"Bahnschrift SemiBold\";\n"
                                              "margin:5px;")
        self.user_login_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.user_login_heading.setObjectName("user_login_heading")
        self.logingrid_layout.addWidget(self.user_login_heading, 0, 0, 1, 2)
        self.test_portal_heading = QtWidgets.QLabel(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_portal_heading.sizePolicy().hasHeightForWidth())
        self.test_portal_heading.setSizePolicy(sizePolicy)
        self.test_portal_heading.setStyleSheet("color: rgb(241, 241, 241);\n"
                                               "\n"
                                               "font: 25 18pt \"Bahnschrift Light Condensed\";\n"
                                               "margin:5px;")
        self.test_portal_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.test_portal_heading.setObjectName("test_portal_heading")
        self.logingrid_layout.addWidget(self.test_portal_heading, 1, 0, 1, 2)
        self.email_lineEdit = QtWidgets.QLineEdit(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_lineEdit.sizePolicy().hasHeightForWidth())
        self.email_lineEdit.setSizePolicy(sizePolicy)
        self.email_lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.email_lineEdit.setStyleSheet("color: rgb(241, 241, 241);\n"
                                       "font: 25 12pt \"Bahnschrift Light\";\n"
                                       "margin:5px;\n"
                                       "background-color: rgb(48, 78, 151 0.73);\n"
                                       "border:0px;\n"
                                       "")
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.logingrid_layout.addWidget(self.email_lineEdit, 2, 0, 1, 2)
        self.email_underline = QtWidgets.QLineEdit(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_underline.sizePolicy().hasHeightForWidth())
        self.email_underline.setSizePolicy(sizePolicy)
        self.email_underline.setMinimumSize(QtCore.QSize(300, 0))
        self.email_underline.setMaximumSize(QtCore.QSize(240, 1))
        self.email_underline.setStyleSheet("color: rgb(241, 241, 241);\n"
                                           "font: 25 12pt \"Bahnschrift Light\";\n"
                                           "margin:0px;\n"
                                           "border: 1px solid white;")
        self.email_underline.setEchoMode(QtWidgets.QLineEdit.Password)
        self.email_underline.setPlaceholderText("")
        self.email_underline.setObjectName("email_underline")
        self.logingrid_layout.addWidget(self.email_underline, 3, 0, 1, 2)
        self.password_line_edit = QtWidgets.QLineEdit(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_line_edit.sizePolicy().hasHeightForWidth())
        self.password_line_edit.setSizePolicy(sizePolicy)
        self.password_line_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.password_line_edit.setStyleSheet("color: rgb(241, 241, 241);\n"
                                              "font: 25 12pt \"Bahnschrift Light\";\n"
                                              "margin:5px;\n"
                                              "background-color: rgb(48, 78, 151 0.73);\n"
                                              "border:0px;")
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line_edit.setObjectName("password_line_edit")
        self.logingrid_layout.addWidget(self.password_line_edit, 4, 0, 1, 2)
        self.password_underline = QtWidgets.QLineEdit(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_underline.sizePolicy().hasHeightForWidth())
        self.password_underline.setSizePolicy(sizePolicy)
        self.password_underline.setMinimumSize(QtCore.QSize(300, 0))
        self.password_underline.setMaximumSize(QtCore.QSize(240, 1))
        self.password_underline.setStyleSheet("color: rgb(241, 241, 241);\n"
                                              "font: 25 12pt \"Bahnschrift Light\";\n"
                                              "margin:0px;\n"
                                              "border: 1px solid white;")
        self.password_underline.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_underline.setPlaceholderText("")
        self.password_underline.setObjectName("password_underline")
        self.logingrid_layout.addWidget(self.password_underline, 5, 0, 1, 2)
        self.remember_me_checkbox = QtWidgets.QCheckBox(self.login_form)
        self.remember_me_checkbox.setMinimumSize(QtCore.QSize(100, 0))
        self.remember_me_checkbox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.remember_me_checkbox.setStyleSheet("color: rgb(241, 241, 241);\n"
                                                "font: 10pt \"Bahnschrift Light\";margin:5px;")
        self.remember_me_checkbox.setObjectName("remember_me_checkbox")
        self.logingrid_layout.addWidget(self.remember_me_checkbox, 6, 0, 1, 1)
        self.forget_pass_btn = QtWidgets.QPushButton(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forget_pass_btn.sizePolicy().hasHeightForWidth())
        self.forget_pass_btn.setSizePolicy(sizePolicy)
        self.forget_pass_btn.setMinimumSize(QtCore.QSize(150, 30))
        self.forget_pass_btn.setMaximumSize(QtCore.QSize(150, 30))
        self.forget_pass_btn.setStyleSheet("background-color: rgb(48, 78, 151);\n"
                                           "\n"
                                           "border:0px;\n"
                                           "border-shadow:0px;\n"
                                           "color: rgb(241, 241, 241);\n"
                                           "font: 10pt \"Bahnschrift Light\";margin:5px;\n"
                                           "vertical-align: center;\n"
                                           "horizontal-align: center;")
        self.forget_pass_btn.setAutoDefault(False)
        self.forget_pass_btn.setFlat(False)
        self.forget_pass_btn.setObjectName("forget_pass_btn")
        self.logingrid_layout.addWidget(self.forget_pass_btn, 6, 1, 1, 1)
        self.login_btn = QtWidgets.QPushButton(self.login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMinimumSize(QtCore.QSize(250, 40))
        self.login_btn.setMaximumSize(QtCore.QSize(100, 40))
        self.login_btn.setStyleSheet("background-color: rgb(111, 168, 68);\n"
                                     "border-radius: 15px;\n"
                                     "color: rgb(241, 241, 241);\n"
                                     "font:  bold 10pt \"Bahnschrift Light\";margin:5px;\n"
                                     "vertical-align: center;\n"
                                     "horizontal-align: center;")
        self.login_btn.setAutoDefault(False)
        self.login_btn.setFlat(False)
        self.login_btn.setObjectName("login_btn")
        self.logingrid_layout.addWidget(self.login_btn, 7, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.error_label = QtWidgets.QLabel(self.login_form)
        self.error_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_label.sizePolicy().hasHeightForWidth())
        self.error_label.setSizePolicy(sizePolicy)
        self.error_label.setMinimumSize(QtCore.QSize(200, 0))
        self.error_label.setStyleSheet("color: rgb(255, 0, 0);\n"
                                       "font: 25 12pt \"Bahnschrift Light\";\n"
                                       "margin:5px;")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.logingrid_layout.addWidget(self.error_label, 8, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.logingrid_layout)
        self.horizontalLayout.addWidget(self.login_form, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.logo_side_bar = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_side_bar.sizePolicy().hasHeightForWidth())
        self.logo_side_bar.setSizePolicy(sizePolicy)
        self.logo_side_bar.setMinimumSize(QtCore.QSize(150, 0))
        self.logo_side_bar.setStyleSheet("")
        self.logo_side_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_side_bar.setLineWidth(0)
        self.logo_side_bar.setObjectName("logo_side_bar")
        self.gridLayout = QtWidgets.QGridLayout(self.logo_side_bar)
        self.gridLayout.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.hunar_logo = QtWidgets.QLabel(self.logo_side_bar)
        self.hunar_logo.setMinimumSize(QtCore.QSize(80, 120))
        self.hunar_logo.setMaximumSize(QtCore.QSize(80, 120))
        self.hunar_logo.setStyleSheet("background-image: url(:/icons/icons/backgrounds/Asset 7-100.jpg);\n"
                                      "background-repeat: no-repeat; \n"
                                      "\n"
                                      " background-position: right;\n"
                                      "margin:5px;\n"
                                      "")
        self.hunar_logo.setText("")
        self.hunar_logo.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing)
        self.hunar_logo.setObjectName("hunar_logo")
        self.gridLayout.addWidget(self.hunar_logo, 0, 0, 1, 1, QtCore.Qt.AlignRight | QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.logo_side_bar)
        self.verticalLayout_2.addWidget(self.main_frame)
        self.verticalLayout.addWidget(self.border_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.RAAS_heading_label.setText(_translate("MainWindow", "RAAS"))
        self.ET_label.setText(_translate("MainWindow", "INSTITUTE OF EMERGING TECHNOLOGIES"))
        self.user_login_heading.setText(_translate("MainWindow", "ADMIN LOGIN"))
        self.test_portal_heading.setText(_translate("MainWindow", "Welcome to the Admin Portal"))
        self.email_lineEdit.setPlaceholderText(_translate("MainWindow", "Email"))
        self.password_line_edit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.remember_me_checkbox.setText(_translate("MainWindow", "Remember"))
        self.forget_pass_btn.setText(_translate("MainWindow", "Forgot your password?"))
        self.login_btn.setText(_translate("MainWindow", "LOGIN"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
